
# image:
#   file: .gitpod.Dockerfile
tasks:
  - command: gp await-port 5555 && sleep 3 && gp preview $(gp url 5555)/src/index.html
  - init: npm install -g eslint bower && bower install
    command: npm -g install bower && bower install
ports:
  - port: 5555
    onOpen: open-browser
vscode:
  extensions:
    - yandeu.five-server
    - codezombiech.gitignore
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - buianhthang.gitflow
    - KnisterPeter.vscode-github
    - felipecaputo.git-project-managergithub:
    - mhutchie.git-graph  prebuilds:
# enable for the master/default branch (defaults to true)
    - pinage404.git-extension-pack  master: true
    - eamodio.gitlens# enable for all branches in this repo (defaults to false)
  branches: true
# enable for pull requests coming from this repo (defaults to true)
  pullRequests: true
# enable for pull requests coming from forks (defaults to false)
  pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
  addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
  addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
  addLabel: prebuilt-in-gitpod
