image:
  file: .gitpod.Dockerfile
tasks:
  - command: gp await-port 3000 && sleep 3 && gp preview $(gp url 3000)/src/index.html
  - init: npm install -g eslint bower && npm install
    command: npm start
ports:
  - port: 3000
    onOpen: ignore
