/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Button } from './button';
import { InputField } from './inputField';


export interface Card { 
    actionSheetButtons?: Array<Button>;
    /**
     * Smaller square image
     */
    avatar?: string;
    /**
     * Smaller circular image
     */
    avatarCircular?: string;
    /**
     * Ex: #f2f2f2
     */
    backgroundColor?: string;
    buttons?: Array<Button>;
    buttonsSecondary?: Array<Button>;
    /**
     * Ex: Content
     */
    content?: string;
    /**
     * Ex: Title
     */
    headerTitle?: string;
    /**
     * HTML for the entire card.
     */
    html?: string;
    /**
     * Ex: <div>Content</div>
     */
    htmlContent?: string;
    /**
     * HTML element id
     */
    id: string;
    /**
     * Larger image of variable dimensions
     */
    image?: string;
    inputFields?: Array<InputField>;
    /**
     * Ex: ion-refresh
     */
    ionIcon?: string;
    /**
     * A link to a web page or something. Not much more to say about that.
     */
    link?: string;
    /**
     * Key value pairs derived from user input fields, button clicks, or preset defaults
     */
    parameters?: any;
    relatedCards?: Array<Card>;
    /**
     * Button that the user clicked and the provided function parameters
     */
    selectedButton?: Button;
    /**
     * Ex: sharingBody
     */
    sharingBody?: string;
    sharingButtons?: Array<Button>;
    /**
     * Ex: sharingTitle
     */
    sharingTitle?: string;
    /**
     * Ex: subTitle
     */
    subHeader?: string;
    /**
     * Ex: subTitle
     */
    subTitle?: string;
    /**
     * Ex: Title
     */
    title?: string;
}
