/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Friend {
    /**
     * What do you expect?
     */
    "id": number;
    /**
     * What do you expect?
     */
    "initiatorUserId": number;
    /**
     * What do you expect?
     */
    "friendUserId": number;
    /**
     * What do you expect?
     */
    "isConfirmed": number;
    /**
     * What do you expect?
     */
    "isLimited": number;
    /**
     * What do you expect?
     */
    "dateCreated": string;
    /**
     * Additional friend key-value data
     */
    "metaDataArray"?: Array<any>;
}

