/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InputField {
    /**
     * What do you expect?
     */
    "displayName": string;
    /**
     * What do you expect?
     */
    "helpText"?: string;
    /**
     * What do you expect?
     */
    "hint"?: string;
    /**
     * What do you expect?
     */
    "icon"?: string;
    /**
     * HTML element id
     */
    "id"?: string;
    /**
     * What do you expect?
     */
    "image"?: string;
    /**
     * What do you expect?
     */
    "key"?: string;
    /**
     * What do you expect?
     */
    "labelLeft"?: string;
    /**
     * What do you expect?
     */
    "labelRight"?: string;
    /**
     * What do you expect?
     */
    "link"?: string;
    /**
     * What do you expect?
     */
    "maxLength"?: number;
    /**
     * What do you expect?
     */
    "maxValue"?: number;
    /**
     * What do you expect?
     */
    "minLength"?: number;
    /**
     * What do you expect?
     */
    "minValue"?: number;
    /**
     * Selector list options
     */
    "options"?: Array<string>;
    /**
     * Ex: Title
     */
    "placeholder"?: string;
    /**
     * What do you expect?
     */
    "postUrl"?: string;
    /**
     * What do you expect?
     */
    "required"?: boolean;
    /**
     * Ex: Title
     */
    "show"?: boolean;
    "submitButton"?: models.Button;
    /**
     * Options: check_box, date, email, number, postal_code, select_option, string, switch, text_area, unit, variable_category
     */
    "type": string;
    /**
     * See http://html5pattern.com/ for examples
     */
    "validationPattern"?: string;
    /**
     * What do you expect?
     */
    "value"?: string;
}

