/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MeasurementSet {
    /**
     * Options: MEAN, SUM
     */
    "combinationOperation"?: string;
    /**
     * Array of timestamps, values, and optional notes
     */
    "measurementItems": Array<models.MeasurementItem>;
    /**
     * Name of the application or device used to record the measurement values
     */
    "sourceName": string;
    /**
     * Unit of measurement
     */
    "unitAbbreviatedName": string;
    /**
     * Options: Activity, Books, Causes of Illness, Cognitive Performance, Conditions, Emotions, Environment, Foods, Goals, Locations, Miscellaneous, Movies and TV, Music, Nutrients, Payments, Physical Activities, Physique, Sleep, Social Interactions, Software, Symptoms, Treatments, Vital Signs
     */
    "variableCategoryName"?: string;
    /**
     * ORIGINAL name of the variable for which we are creating the measurement records
     */
    "variableName": string;
    /**
     * UPC or other barcode scan result
     */
    "upc"?: string;
}

