/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface StudyImages {
    /**
     * Ex: https://maxcdn.icons8.com/Color/PNG/96/Household/sleeping_in_bed-96.png
     */
    "causeVariableImageUrl"?: string;
    /**
     * Ex: ion-ios-cloudy-night-outline
     */
    "causeVariableIonIcon"?: string;
    /**
     * Ex: https://maxcdn.icons8.com/Color/PNG/96/Cinema/theatre_mask-96.png
     */
    "effectVariableImageUrl"?: string;
    /**
     * Ex: ion-happy-outline
     */
    "effectVariableIonIcon"?: string;
    /**
     * Ex: https://s3.amazonaws.com/quantimodo-docs/images/gauge-moderately-positive-relationship.png
     */
    "gaugeImage": string;
    /**
     * Ex: https://s3.amazonaws.com/quantimodo-docs/images/gauge-moderately-positive-relationship-200-200.png
     */
    "gaugeImageSquare": string;
    /**
     * Image with gauge and category images
     */
    "gaugeSharingImageUrl"?: string;
    /**
     * Ex: https://s3-us-west-1.amazonaws.com/qmimages/variable_categories_gauges_logo_background/gauge-moderately-positive-relationship_sleep_emotions_logo_background.png
     */
    "imageUrl": string;
    /**
     * Image with robot and category images
     */
    "robotSharingImageUrl"?: string;
    /**
     * Avatar of the principal investigator
     */
    "avatar"?: string;
}

