/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface VariableCategory {
    /**
     * Ex: mood
     */
    "appType"?: string;
    /**
     * Ex: false
     */
    "causeOnly"?: boolean;
    /**
     * Ex: MEAN
     */
    "combinationOperation"?: string;
    /**
     * UTC ISO 8601 YYYY-MM-DDThh:mm:ss
     */
    "createdTime"?: string;
    /**
     * Ex: /5
     */
    "unitAbbreviatedName"?: string;
    /**
     * Ex: 10
     */
    "unitId"?: number;
    /**
     * User-Defined Variable Setting: The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.  Unit: Seconds
     */
    "durationOfAction"?: number;
    /**
     * Ex: -1. Unit: Variable category default unit.
     */
    "fillingValue"?: number;
    /**
     * Ex: What emotion do you want to rate?
     */
    "helpText"?: string;
    /**
     * Ex: 1
     */
    "id"?: number;
    /**
     * Ex: https://maxcdn.icons8.com/Color/PNG/96/Cinema/theatre_mask-96.png
     */
    "imageUrl"?: string;
    /**
     * Ex: ion-happy-outline
     */
    "ionIcon"?: string;
    /**
     * Ex: true
     */
    "manualTracking"?: boolean;
    /**
     * Unit: Variable category default unit.
     */
    "maximumAllowedValue"?: string;
    /**
     * Ex: rating
     */
    "measurementSynonymSingularLowercase"?: string;
    /**
     * Unit: Variable category default unit.
     */
    "minimumAllowedValue"?: string;
    /**
     * Ex: Do you have any emotions that fluctuate regularly?  If so, add them so I can try to determine which factors are influencing them.
     */
    "moreInfo"?: string;
    /**
     * Category name
     */
    "name": string;
    /**
     * Ex: 0
     */
    "onsetDelay"?: number;
    /**
     * Ex: true
     */
    "outcome"?: boolean;
    /**
     * Ex: img/variable_categories/emotions.png
     */
    "pngPath"?: string;
    /**
     * Ex: https://web.quantimo.do/img/variable_categories/emotions.png
     */
    "pngUrl"?: string;
    /**
     * Ex: true
     */
    "_public"?: boolean;
    /**
     * Ex: img/variable_categories/emotions.svg
     */
    "svgPath"?: string;
    /**
     * Ex: https://web.quantimo.do/img/variable_categories/emotions.svg
     */
    "svgUrl"?: string;
    /**
     * Ex: 1
     */
    "updated"?: number;
    /**
     * UTC ISO 8601 YYYY-MM-DDThh:mm:ss
     */
    "updatedTime"?: string;
    /**
     * Options: Activity, Books, Causes of Illness, Cognitive Performance, Conditions, Emotions, Environment, Foods, Goals, Locations, Miscellaneous, Movies and TV, Music, Nutrients, Payments, Physical Activities, Physique, Sleep, Social Interactions, Software, Symptoms, Treatments, Vital Signs
     */
    "variableCategoryName"?: string;
    /**
     * Ex: Emotion
     */
    "variableCategoryNameSingular"?: string;
}

