export * from './ActivitiesApi';
import { ActivitiesApi } from './ActivitiesApi';
export * from './AnalyticsApi';
import { AnalyticsApi } from './AnalyticsApi';
export * from './AppSettingsApi';
import { AppSettingsApi } from './AppSettingsApi';
export * from './AuthenticationApi';
import { AuthenticationApi } from './AuthenticationApi';
export * from './ConnectorsApi';
import { ConnectorsApi } from './ConnectorsApi';
export * from './FeedApi';
import { FeedApi } from './FeedApi';
export * from './FriendsApi';
import { FriendsApi } from './FriendsApi';
export * from './GroupsApi';
import { GroupsApi } from './GroupsApi';
export * from './MeasurementsApi';
import { MeasurementsApi } from './MeasurementsApi';
export * from './MessagesApi';
import { MessagesApi } from './MessagesApi';
export * from './NotificationsApi';
import { NotificationsApi } from './NotificationsApi';
export * from './RemindersApi';
import { RemindersApi } from './RemindersApi';
export * from './SharesApi';
import { SharesApi } from './SharesApi';
export * from './StudiesApi';
import { StudiesApi } from './StudiesApi';
export * from './UnitsApi';
import { UnitsApi } from './UnitsApi';
export * from './UserApi';
import { UserApi } from './UserApi';
export * from './VariablesApi';
import { VariablesApi } from './VariablesApi';
export * from './XprofileApi';
import { XprofileApi } from './XprofileApi';
export const APIS = [ActivitiesApi, AnalyticsApi, AppSettingsApi, AuthenticationApi, ConnectorsApi, FeedApi, FriendsApi, GroupsApi, MeasurementsApi, MessagesApi, NotificationsApi, RemindersApi, SharesApi, StudiesApi, UnitsApi, UserApi, VariablesApi, XprofileApi];
