/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering */

export class VariablesApi {
    protected basePath = 'https://app.quantimo.do/api';
    public defaultHeaders : any = {};

    static $inject: string[] = ['$http', '$httpParamSerializer', 'basePath'];

    constructor(protected $http: ng.IHttpService, protected $httpParamSerializer?: (d: any) => any, basePath?: string) {
        if (basePath !== undefined) {
            this.basePath = basePath;
        }
    }

    /**
     * Delete previously created user tags or ingredients.
     * @summary Delete user tag or ingredient
     * @param taggedVariableId Id of the tagged variable (i.e. Lollipop) you would like to get variables it can be tagged with (i.e. Sugar).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param tagVariableId Id of the tag variable (i.e. Sugar) you would like to get variables it can be tagged to (i.e. Lollipop).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     */
    public deleteUserTag (taggedVariableId?: number, tagVariableId?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.CommonResponse> {
        const localVarPath = this.basePath + '/v3/userTags/delete';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (taggedVariableId !== undefined) {
            queryParameters['taggedVariableId'] = taggedVariableId;
        }

        if (tagVariableId !== undefined) {
            queryParameters['tagVariableId'] = tagVariableId;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Users can delete all of their measurements for a variable
     * @summary Delete All Measurements For Variable
     * @param variableId Id of the variable whose measurements should be deleted
     */
    public deleteUserVariable (variableId: models.UserVariableDelete, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/v3/userVariables/delete';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'variableId' is not null or undefined
        if (variableId === null || variableId === undefined) {
            throw new Error('Required parameter variableId was null or undefined when calling deleteUserVariable.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'DELETE',
            url: localVarPath,
            data: variableId,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * The variable categories include Activity, Causes of Illness, Cognitive Performance, Conditions, Environment, Foods, Location, Miscellaneous, Mood, Nutrition, Physical Activity, Physique, Sleep, Social Interactions, Symptoms, Treatments, Vital Signs, and Goals.
     * @summary Variable categories
     */
    public getVariableCategories (extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.VariableCategory>> {
        const localVarPath = this.basePath + '/v3/variableCategories';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Get variables. If the user has specified variable settings, these are provided instead of the common variable defaults.
     * @summary Get variables along with related user-specific analysis settings and statistics
     * @param includeCharts Highcharts configs that can be used if you have highcharts.js included on the page.  This only works if the id or name query parameter is also provided.
     * @param numberOfRawMeasurements Filter variables by the total number of measurements that they have. This could be used of you want to filter or sort by popularity.
     * @param userId User&#39;s id
     * @param variableCategoryName Options: Activities, Books, Causes of Illness, Cognitive Performance, Conditions, Emotions, Environment, Foods, Location, Miscellaneous, Movies and TV, Music, Nutrients, Payments, Physical Activity, Physique, Sleep, Social Interactions, Software, Symptoms, Treatments, Vital Signs, Goals
     * @param name Name of the variable. To get results matching a substring, add % as a wildcard as the first and/or last character of a query string parameter. In order to get variables that contain &#x60;Mood&#x60;, the following query should be used: ?variableName&#x3D;%Mood%
     * @param variableName Name of the variable you want measurements for
     * @param updatedAt When the record was last updated. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss datetime format. Time zone should be UTC and not local.
     * @param sourceName ID of the source you want measurements for (supports exact name match only)
     * @param earliestMeasurementTime Excluded records with measurement times earlier than this value. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format. Time zone should be UTC and not local.
     * @param latestMeasurementTime Excluded records with measurement times later than this value. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format. Time zone should be UTC and not local.
     * @param id Common variable id
     * @param lastSourceName Limit variables to those which measurements were last submitted by a specific source. So if you have a client application and you only want variables that were last updated by your app, you can include the name of your app here
     * @param limit The LIMIT is used to limit the number of results returned. So if youhave 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. The maximum limit is 200 records.
     * @param offset OFFSET says to skip that many rows before beginning to return rows to the client. OFFSET 0 is the same as omitting the OFFSET clause.If both OFFSET and LIMIT appear, then OFFSET rows are skipped before starting to count the LIMIT rows that are returned.
     * @param sort Sort by one of the listed field names. If the field name is prefixed with &#x60;-&#x60;, it will sort in descending order.
     * @param includePublic Include variables the user has no measurements for
     * @param manualTracking Only include variables tracked manually by the user
     * @param clientId Your QuantiModo client id can be obtained by creating an app at https://builder.quantimo.do
     * @param upc UPC or other barcode scan result
     * @param effectOrCause Provided variable is the effect or cause
     * @param publicEffectOrCause Ex: 
     * @param exactMatch Require exact match
     * @param variableCategoryId Ex: 13
     * @param includePrivate Include user-specific variables in results
     * @param searchPhrase Ex: %Body Fat%
     * @param synonyms Ex: McDonalds hotcake
     * @param taggedVariableId Id of the tagged variable (i.e. Lollipop) you would like to get variables it can be tagged with (i.e. Sugar).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param tagVariableId Id of the tag variable (i.e. Sugar) you would like to get variables it can be tagged to (i.e. Lollipop).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param joinVariableId Id of the variable you would like to get variables that can be joined to.  This is used to merge duplicate variables.   If joinVariableId is specified, this returns only variables eligible to be joined to the variable specified by the joinVariableId.
     * @param parentUserTagVariableId Id of the parent category variable (i.e. Fruit) you would like to get eligible child sub-type variables (i.e. Apple) for.  Child variable measurements will be included in analysis of the parent variable.  For instance, a child sub-type of the parent category Fruit could be Apple.  When Apple is tagged with the parent category Fruit, Apple measurements will be included when Fruit is analyzed.
     * @param childUserTagVariableId Id of the child sub-type variable (i.e. Apple) you would like to get eligible parent variables (i.e. Fruit) for.  Child variable measurements will be included in analysis of the parent variable.  For instance, a child sub-type of the parent category Fruit could be Apple. When Apple is tagged with the parent category Fruit, Apple measurements will be included when Fruit is analyzed.
     * @param ingredientUserTagVariableId Id of the ingredient variable (i.e. Fructose)  you would like to get eligible ingredientOf variables (i.e. Apple) for.  IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredientOf of variable Fruit could be Apple.
     * @param ingredientOfUserTagVariableId Id of the ingredientOf variable (i.e. Apple) you would like to get eligible ingredient variables (i.e. Fructose) for.  IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredientOf of variable Fruit could be Apple.
     * @param commonOnly Return only public and aggregated common variable data instead of user-specific variables
     * @param userOnly Return only user-specific variables and data, excluding common aggregated variable data
     * @param includeTags Return parent, child, duplicate, and ingredient variables
     * @param recalculate Recalculate instead of using cached analysis
     * @param variableId Ex: 13
     * @param concise Only return field required for variable auto-complete searches.  The smaller size allows for storing more variable results locally reducing API requests.
     * @param refresh Regenerate charts instead of getting from the cache
     */
    public getVariables (includeCharts?: boolean, numberOfRawMeasurements?: string, userId?: number, variableCategoryName?: string, name?: string, variableName?: string, updatedAt?: string, sourceName?: string, earliestMeasurementTime?: string, latestMeasurementTime?: string, id?: number, lastSourceName?: string, limit?: number, offset?: number, sort?: string, includePublic?: boolean, manualTracking?: boolean, clientId?: string, upc?: string, effectOrCause?: string, publicEffectOrCause?: string, exactMatch?: boolean, variableCategoryId?: number, includePrivate?: boolean, searchPhrase?: string, synonyms?: string, taggedVariableId?: number, tagVariableId?: number, joinVariableId?: number, parentUserTagVariableId?: number, childUserTagVariableId?: number, ingredientUserTagVariableId?: number, ingredientOfUserTagVariableId?: number, commonOnly?: boolean, userOnly?: boolean, includeTags?: boolean, recalculate?: boolean, variableId?: number, concise?: boolean, refresh?: boolean, extraHttpRequestParams?: any ) : ng.IHttpPromise<Array<models.Variable>> {
        const localVarPath = this.basePath + '/v3/variables';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        if (includeCharts !== undefined) {
            queryParameters['includeCharts'] = includeCharts;
        }

        if (numberOfRawMeasurements !== undefined) {
            queryParameters['numberOfRawMeasurements'] = numberOfRawMeasurements;
        }

        if (userId !== undefined) {
            queryParameters['userId'] = userId;
        }

        if (variableCategoryName !== undefined) {
            queryParameters['variableCategoryName'] = variableCategoryName;
        }

        if (name !== undefined) {
            queryParameters['name'] = name;
        }

        if (variableName !== undefined) {
            queryParameters['variableName'] = variableName;
        }

        if (updatedAt !== undefined) {
            queryParameters['updatedAt'] = updatedAt;
        }

        if (sourceName !== undefined) {
            queryParameters['sourceName'] = sourceName;
        }

        if (earliestMeasurementTime !== undefined) {
            queryParameters['earliestMeasurementTime'] = earliestMeasurementTime;
        }

        if (latestMeasurementTime !== undefined) {
            queryParameters['latestMeasurementTime'] = latestMeasurementTime;
        }

        if (id !== undefined) {
            queryParameters['id'] = id;
        }

        if (lastSourceName !== undefined) {
            queryParameters['lastSourceName'] = lastSourceName;
        }

        if (limit !== undefined) {
            queryParameters['limit'] = limit;
        }

        if (offset !== undefined) {
            queryParameters['offset'] = offset;
        }

        if (sort !== undefined) {
            queryParameters['sort'] = sort;
        }

        if (includePublic !== undefined) {
            queryParameters['includePublic'] = includePublic;
        }

        if (manualTracking !== undefined) {
            queryParameters['manualTracking'] = manualTracking;
        }

        if (clientId !== undefined) {
            queryParameters['clientId'] = clientId;
        }

        if (upc !== undefined) {
            queryParameters['upc'] = upc;
        }

        if (effectOrCause !== undefined) {
            queryParameters['effectOrCause'] = effectOrCause;
        }

        if (publicEffectOrCause !== undefined) {
            queryParameters['publicEffectOrCause'] = publicEffectOrCause;
        }

        if (exactMatch !== undefined) {
            queryParameters['exactMatch'] = exactMatch;
        }

        if (variableCategoryId !== undefined) {
            queryParameters['variableCategoryId'] = variableCategoryId;
        }

        if (includePrivate !== undefined) {
            queryParameters['includePrivate'] = includePrivate;
        }

        if (searchPhrase !== undefined) {
            queryParameters['searchPhrase'] = searchPhrase;
        }

        if (synonyms !== undefined) {
            queryParameters['synonyms'] = synonyms;
        }

        if (taggedVariableId !== undefined) {
            queryParameters['taggedVariableId'] = taggedVariableId;
        }

        if (tagVariableId !== undefined) {
            queryParameters['tagVariableId'] = tagVariableId;
        }

        if (joinVariableId !== undefined) {
            queryParameters['joinVariableId'] = joinVariableId;
        }

        if (parentUserTagVariableId !== undefined) {
            queryParameters['parentUserTagVariableId'] = parentUserTagVariableId;
        }

        if (childUserTagVariableId !== undefined) {
            queryParameters['childUserTagVariableId'] = childUserTagVariableId;
        }

        if (ingredientUserTagVariableId !== undefined) {
            queryParameters['ingredientUserTagVariableId'] = ingredientUserTagVariableId;
        }

        if (ingredientOfUserTagVariableId !== undefined) {
            queryParameters['ingredientOfUserTagVariableId'] = ingredientOfUserTagVariableId;
        }

        if (commonOnly !== undefined) {
            queryParameters['commonOnly'] = commonOnly;
        }

        if (userOnly !== undefined) {
            queryParameters['userOnly'] = userOnly;
        }

        if (includeTags !== undefined) {
            queryParameters['includeTags'] = includeTags;
        }

        if (recalculate !== undefined) {
            queryParameters['recalculate'] = recalculate;
        }

        if (variableId !== undefined) {
            queryParameters['variableId'] = variableId;
        }

        if (concise !== undefined) {
            queryParameters['concise'] = concise;
        }

        if (refresh !== undefined) {
            queryParameters['refresh'] = refresh;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'GET',
            url: localVarPath,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * This endpoint allows users to tag foods with their ingredients.  This information will then be used to infer the user intake of the different ingredients by just entering the foods. The inferred intake levels will then be used to determine the effects of different nutrients on the user during analysis.
     * @summary Post or update user tags or ingredients
     * @param body Contains the new user tag data
     * @param userId User&#39;s id
     */
    public postUserTags (body: models.UserTag, userId?: number, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.CommonResponse> {
        const localVarPath = this.basePath + '/v3/userTags';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postUserTags.');
        }

        if (userId !== undefined) {
            queryParameters['userId'] = userId;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: body,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Users can change the parameters used in analysis of that variable such as the expected duration of action for a variable to have an effect, the estimated delay before the onset of action. In order to filter out erroneous data, they are able to set the maximum and minimum reasonable daily values for a variable.
     * @summary Update User Settings for a Variable
     * @param userVariables Variable user settings data
     * @param includePrivate Include user-specific variables in results
     * @param clientId Your QuantiModo client id can be obtained by creating an app at https://builder.quantimo.do
     * @param includePublic Include variables the user has no measurements for
     * @param searchPhrase Ex: %Body Fat%
     * @param exactMatch Require exact match
     * @param manualTracking Only include variables tracked manually by the user
     * @param variableCategoryName Options: Activities, Books, Causes of Illness, Cognitive Performance, Conditions, Emotions, Environment, Foods, Location, Miscellaneous, Movies and TV, Music, Nutrients, Payments, Physical Activity, Physique, Sleep, Social Interactions, Software, Symptoms, Treatments, Vital Signs, Goals
     * @param variableCategoryId Ex: 13
     * @param synonyms Ex: McDonalds hotcake
     */
    public postUserVariables (userVariables: Array<models.Variable>, includePrivate?: boolean, clientId?: string, includePublic?: boolean, searchPhrase?: string, exactMatch?: boolean, manualTracking?: boolean, variableCategoryName?: string, variableCategoryId?: number, synonyms?: string, extraHttpRequestParams?: any ) : ng.IHttpPromise<models.CommonResponse> {
        const localVarPath = this.basePath + '/v3/variables';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'userVariables' is not null or undefined
        if (userVariables === null || userVariables === undefined) {
            throw new Error('Required parameter userVariables was null or undefined when calling postUserVariables.');
        }

        if (includePrivate !== undefined) {
            queryParameters['includePrivate'] = includePrivate;
        }

        if (clientId !== undefined) {
            queryParameters['clientId'] = clientId;
        }

        if (includePublic !== undefined) {
            queryParameters['includePublic'] = includePublic;
        }

        if (searchPhrase !== undefined) {
            queryParameters['searchPhrase'] = searchPhrase;
        }

        if (exactMatch !== undefined) {
            queryParameters['exactMatch'] = exactMatch;
        }

        if (manualTracking !== undefined) {
            queryParameters['manualTracking'] = manualTracking;
        }

        if (variableCategoryName !== undefined) {
            queryParameters['variableCategoryName'] = variableCategoryName;
        }

        if (variableCategoryId !== undefined) {
            queryParameters['variableCategoryId'] = variableCategoryId;
        }

        if (synonyms !== undefined) {
            queryParameters['synonyms'] = synonyms;
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: userVariables,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
    /**
     * Reset user settings for a variable to defaults
     * @summary Reset user settings for a variable to defaults
     * @param variableId Id of the variable whose measurements should be deleted
     */
    public resetUserVariableSettings (variableId: models.UserVariableDelete, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {
        const localVarPath = this.basePath + '/v3/userVariables/reset';

        let queryParameters: any = {};
        let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);
        // verify required parameter 'variableId' is not null or undefined
        if (variableId === null || variableId === undefined) {
            throw new Error('Required parameter variableId was null or undefined when calling resetUserVariableSettings.');
        }

        let httpRequestParams: ng.IRequestConfig = {
            method: 'POST',
            url: localVarPath,
            data: variableId,
            params: queryParameters,
            headers: headerParams
        };

        if (extraHttpRequestParams) {
            httpRequestParams = (<any>Object).assign(httpRequestParams, extraHttpRequestParams);
        }

        return this.$http(httpRequestParams);
    }
}
