name: Upload to qm-public on DO Spaces

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'nyc3'   # optional: defaults to us-east-1
        AWS_S3_ENDPOINT: https://sfo2.digitaloceanspaces.com
        #DEST_DIR: 'css'
        SOURCE_DIR: 'src'      # optional: defaults to entire repository
