"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./activities.service"));
var activities_service_1 = require("./activities.service");
__export(require("./analytics.service"));
var analytics_service_1 = require("./analytics.service");
__export(require("./appSettings.service"));
var appSettings_service_1 = require("./appSettings.service");
__export(require("./authentication.service"));
var authentication_service_1 = require("./authentication.service");
__export(require("./connectors.service"));
var connectors_service_1 = require("./connectors.service");
__export(require("./feed.service"));
var feed_service_1 = require("./feed.service");
__export(require("./friends.service"));
var friends_service_1 = require("./friends.service");
__export(require("./groups.service"));
var groups_service_1 = require("./groups.service");
__export(require("./measurements.service"));
var measurements_service_1 = require("./measurements.service");
__export(require("./messages.service"));
var messages_service_1 = require("./messages.service");
__export(require("./notifications.service"));
var notifications_service_1 = require("./notifications.service");
__export(require("./reminders.service"));
var reminders_service_1 = require("./reminders.service");
__export(require("./shares.service"));
var shares_service_1 = require("./shares.service");
__export(require("./studies.service"));
var studies_service_1 = require("./studies.service");
__export(require("./units.service"));
var units_service_1 = require("./units.service");
__export(require("./user.service"));
var user_service_1 = require("./user.service");
__export(require("./variables.service"));
var variables_service_1 = require("./variables.service");
__export(require("./xprofile.service"));
var xprofile_service_1 = require("./xprofile.service");
exports.APIS = [activities_service_1.ActivitiesService, analytics_service_1.AnalyticsService, appSettings_service_1.AppSettingsService, authentication_service_1.AuthenticationService, connectors_service_1.ConnectorsService, feed_service_1.FeedService, friends_service_1.FriendsService, groups_service_1.GroupsService, measurements_service_1.MeasurementsService, messages_service_1.MessagesService, notifications_service_1.NotificationsService, reminders_service_1.RemindersService, shares_service_1.SharesService, studies_service_1.StudiesService, units_service_1.UnitsService, user_service_1.UserService, variables_service_1.VariablesService, xprofile_service_1.XprofileService];
