export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './appSettings.service';
import { AppSettingsService } from './appSettings.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './connectors.service';
import { ConnectorsService } from './connectors.service';
export * from './feed.service';
import { FeedService } from './feed.service';
export * from './friends.service';
import { FriendsService } from './friends.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './measurements.service';
import { MeasurementsService } from './measurements.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './reminders.service';
import { RemindersService } from './reminders.service';
export * from './shares.service';
import { SharesService } from './shares.service';
export * from './studies.service';
import { StudiesService } from './studies.service';
export * from './units.service';
import { UnitsService } from './units.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './variables.service';
import { VariablesService } from './variables.service';
export * from './xprofile.service';
import { XprofileService } from './xprofile.service';
export const APIS = [ActivitiesService, AnalyticsService, AppSettingsService, AuthenticationService, ConnectorsService, FeedService, FriendsService, GroupsService, MeasurementsService, MessagesService, NotificationsService, RemindersService, SharesService, StudiesService, UnitsService, UserService, VariablesService, XprofileService];
