/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CommonResponse } from '../model/commonResponse';
import { UserTag } from '../model/userTag';
import { UserVariableDelete } from '../model/userVariableDelete';
import { Variable } from '../model/variable';
import { VariableCategory } from '../model/variableCategory';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VariablesService {

    protected basePath = 'https://app.quantimo.do/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Delete user tag or ingredient
     * Delete previously created user tags or ingredients.
     * @param taggedVariableId Id of the tagged variable (i.e. Lollipop) you would like to get variables it can be tagged with (i.e. Sugar).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param tagVariableId Id of the tag variable (i.e. Sugar) you would like to get variables it can be tagged to (i.e. Lollipop).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUserTag(taggedVariableId?: number, tagVariableId?: number, observe?: 'body', reportProgress?: boolean): Observable<CommonResponse>;
    public deleteUserTag(taggedVariableId?: number, tagVariableId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CommonResponse>>;
    public deleteUserTag(taggedVariableId?: number, tagVariableId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CommonResponse>>;
    public deleteUserTag(taggedVariableId?: number, tagVariableId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (taggedVariableId !== undefined && taggedVariableId !== null) {
            queryParameters = queryParameters.set('taggedVariableId', <any>taggedVariableId);
        }
        if (tagVariableId !== undefined && tagVariableId !== null) {
            queryParameters = queryParameters.set('tagVariableId', <any>tagVariableId);
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<CommonResponse>(`${this.basePath}/v3/userTags/delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete All Measurements For Variable
     * Users can delete all of their measurements for a variable
     * @param variableId Id of the variable whose measurements should be deleted
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUserVariable(variableId: UserVariableDelete, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteUserVariable(variableId: UserVariableDelete, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteUserVariable(variableId: UserVariableDelete, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteUserVariable(variableId: UserVariableDelete, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (variableId === null || variableId === undefined) {
            throw new Error('Required parameter variableId was null or undefined when calling deleteUserVariable.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.delete<any>(`${this.basePath}/v3/userVariables/delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Variable categories
     * The variable categories include Activity, Causes of Illness, Cognitive Performance, Conditions, Environment, Foods, Location, Miscellaneous, Mood, Nutrition, Physical Activity, Physique, Sleep, Social Interactions, Symptoms, Treatments, Vital Signs, and Goals.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getVariableCategories(observe?: 'body', reportProgress?: boolean): Observable<Array<VariableCategory>>;
    public getVariableCategories(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<VariableCategory>>>;
    public getVariableCategories(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<VariableCategory>>>;
    public getVariableCategories(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<VariableCategory>>(`${this.basePath}/v3/variableCategories`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get variables along with related user-specific analysis settings and statistics
     * Get variables. If the user has specified variable settings, these are provided instead of the common variable defaults.
     * @param includeCharts Highcharts configs that can be used if you have highcharts.js included on the page.  This only works if the id or name query parameter is also provided.
     * @param numberOfRawMeasurements Filter variables by the total number of measurements that they have. This could be used of you want to filter or sort by popularity.
     * @param userId User&#39;s id
     * @param variableCategoryName Options: Activities, Books, Causes of Illness, Cognitive Performance, Conditions, Emotions, Environment, Foods, Location, Miscellaneous, Movies and TV, Music, Nutrients, Payments, Physical Activity, Physique, Sleep, Social Interactions, Software, Symptoms, Treatments, Vital Signs, Goals
     * @param name Name of the variable. To get results matching a substring, add % as a wildcard as the first and/or last character of a query string parameter. In order to get variables that contain &#x60;Mood&#x60;, the following query should be used: ?variableName&#x3D;%Mood%
     * @param variableName Name of the variable you want measurements for
     * @param updatedAt When the record was last updated. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss datetime format. Time zone should be UTC and not local.
     * @param sourceName ID of the source you want measurements for (supports exact name match only)
     * @param earliestMeasurementTime Excluded records with measurement times earlier than this value. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format. Time zone should be UTC and not local.
     * @param latestMeasurementTime Excluded records with measurement times later than this value. Use UTC ISO 8601 YYYY-MM-DDThh:mm:ss  datetime format. Time zone should be UTC and not local.
     * @param id Common variable id
     * @param lastSourceName Limit variables to those which measurements were last submitted by a specific source. So if you have a client application and you only want variables that were last updated by your app, you can include the name of your app here
     * @param limit The LIMIT is used to limit the number of results returned. So if youhave 1000 results, but only want to the first 10, you would set this to 10 and offset to 0. The maximum limit is 200 records.
     * @param offset OFFSET says to skip that many rows before beginning to return rows to the client. OFFSET 0 is the same as omitting the OFFSET clause.If both OFFSET and LIMIT appear, then OFFSET rows are skipped before starting to count the LIMIT rows that are returned.
     * @param sort Sort by one of the listed field names. If the field name is prefixed with &#x60;-&#x60;, it will sort in descending order.
     * @param includePublic Include variables the user has no measurements for
     * @param manualTracking Only include variables tracked manually by the user
     * @param clientId Your QuantiModo client id can be obtained by creating an app at https://builder.quantimo.do
     * @param upc UPC or other barcode scan result
     * @param effectOrCause Provided variable is the effect or cause
     * @param publicEffectOrCause Ex: 
     * @param exactMatch Require exact match
     * @param variableCategoryId Ex: 13
     * @param includePrivate Include user-specific variables in results
     * @param searchPhrase Ex: %Body Fat%
     * @param synonyms Ex: McDonalds hotcake
     * @param taggedVariableId Id of the tagged variable (i.e. Lollipop) you would like to get variables it can be tagged with (i.e. Sugar).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param tagVariableId Id of the tag variable (i.e. Sugar) you would like to get variables it can be tagged to (i.e. Lollipop).  Converted measurements of the tagged variable are included in analysis of the tag variable (i.e. ingredient).
     * @param joinVariableId Id of the variable you would like to get variables that can be joined to.  This is used to merge duplicate variables.   If joinVariableId is specified, this returns only variables eligible to be joined to the variable specified by the joinVariableId.
     * @param parentUserTagVariableId Id of the parent category variable (i.e. Fruit) you would like to get eligible child sub-type variables (i.e. Apple) for.  Child variable measurements will be included in analysis of the parent variable.  For instance, a child sub-type of the parent category Fruit could be Apple.  When Apple is tagged with the parent category Fruit, Apple measurements will be included when Fruit is analyzed.
     * @param childUserTagVariableId Id of the child sub-type variable (i.e. Apple) you would like to get eligible parent variables (i.e. Fruit) for.  Child variable measurements will be included in analysis of the parent variable.  For instance, a child sub-type of the parent category Fruit could be Apple. When Apple is tagged with the parent category Fruit, Apple measurements will be included when Fruit is analyzed.
     * @param ingredientUserTagVariableId Id of the ingredient variable (i.e. Fructose)  you would like to get eligible ingredientOf variables (i.e. Apple) for.  IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredientOf of variable Fruit could be Apple.
     * @param ingredientOfUserTagVariableId Id of the ingredientOf variable (i.e. Apple) you would like to get eligible ingredient variables (i.e. Fructose) for.  IngredientOf variable measurements will be included in analysis of the ingredient variable.  For instance, a ingredientOf of variable Fruit could be Apple.
     * @param commonOnly Return only public and aggregated common variable data instead of user-specific variables
     * @param userOnly Return only user-specific variables and data, excluding common aggregated variable data
     * @param includeTags Return parent, child, duplicate, and ingredient variables
     * @param recalculate Recalculate instead of using cached analysis
     * @param variableId Ex: 13
     * @param concise Only return field required for variable auto-complete searches.  The smaller size allows for storing more variable results locally reducing API requests.
     * @param refresh Regenerate charts instead of getting from the cache
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getVariables(includeCharts?: boolean, numberOfRawMeasurements?: string, userId?: number, variableCategoryName?: string, name?: string, variableName?: string, updatedAt?: string, sourceName?: string, earliestMeasurementTime?: string, latestMeasurementTime?: string, id?: number, lastSourceName?: string, limit?: number, offset?: number, sort?: string, includePublic?: boolean, manualTracking?: boolean, clientId?: string, upc?: string, effectOrCause?: string, publicEffectOrCause?: string, exactMatch?: boolean, variableCategoryId?: number, includePrivate?: boolean, searchPhrase?: string, synonyms?: string, taggedVariableId?: number, tagVariableId?: number, joinVariableId?: number, parentUserTagVariableId?: number, childUserTagVariableId?: number, ingredientUserTagVariableId?: number, ingredientOfUserTagVariableId?: number, commonOnly?: boolean, userOnly?: boolean, includeTags?: boolean, recalculate?: boolean, variableId?: number, concise?: boolean, refresh?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<Variable>>;
    public getVariables(includeCharts?: boolean, numberOfRawMeasurements?: string, userId?: number, variableCategoryName?: string, name?: string, variableName?: string, updatedAt?: string, sourceName?: string, earliestMeasurementTime?: string, latestMeasurementTime?: string, id?: number, lastSourceName?: string, limit?: number, offset?: number, sort?: string, includePublic?: boolean, manualTracking?: boolean, clientId?: string, upc?: string, effectOrCause?: string, publicEffectOrCause?: string, exactMatch?: boolean, variableCategoryId?: number, includePrivate?: boolean, searchPhrase?: string, synonyms?: string, taggedVariableId?: number, tagVariableId?: number, joinVariableId?: number, parentUserTagVariableId?: number, childUserTagVariableId?: number, ingredientUserTagVariableId?: number, ingredientOfUserTagVariableId?: number, commonOnly?: boolean, userOnly?: boolean, includeTags?: boolean, recalculate?: boolean, variableId?: number, concise?: boolean, refresh?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Variable>>>;
    public getVariables(includeCharts?: boolean, numberOfRawMeasurements?: string, userId?: number, variableCategoryName?: string, name?: string, variableName?: string, updatedAt?: string, sourceName?: string, earliestMeasurementTime?: string, latestMeasurementTime?: string, id?: number, lastSourceName?: string, limit?: number, offset?: number, sort?: string, includePublic?: boolean, manualTracking?: boolean, clientId?: string, upc?: string, effectOrCause?: string, publicEffectOrCause?: string, exactMatch?: boolean, variableCategoryId?: number, includePrivate?: boolean, searchPhrase?: string, synonyms?: string, taggedVariableId?: number, tagVariableId?: number, joinVariableId?: number, parentUserTagVariableId?: number, childUserTagVariableId?: number, ingredientUserTagVariableId?: number, ingredientOfUserTagVariableId?: number, commonOnly?: boolean, userOnly?: boolean, includeTags?: boolean, recalculate?: boolean, variableId?: number, concise?: boolean, refresh?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Variable>>>;
    public getVariables(includeCharts?: boolean, numberOfRawMeasurements?: string, userId?: number, variableCategoryName?: string, name?: string, variableName?: string, updatedAt?: string, sourceName?: string, earliestMeasurementTime?: string, latestMeasurementTime?: string, id?: number, lastSourceName?: string, limit?: number, offset?: number, sort?: string, includePublic?: boolean, manualTracking?: boolean, clientId?: string, upc?: string, effectOrCause?: string, publicEffectOrCause?: string, exactMatch?: boolean, variableCategoryId?: number, includePrivate?: boolean, searchPhrase?: string, synonyms?: string, taggedVariableId?: number, tagVariableId?: number, joinVariableId?: number, parentUserTagVariableId?: number, childUserTagVariableId?: number, ingredientUserTagVariableId?: number, ingredientOfUserTagVariableId?: number, commonOnly?: boolean, userOnly?: boolean, includeTags?: boolean, recalculate?: boolean, variableId?: number, concise?: boolean, refresh?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {









































        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (includeCharts !== undefined && includeCharts !== null) {
            queryParameters = queryParameters.set('includeCharts', <any>includeCharts);
        }
        if (numberOfRawMeasurements !== undefined && numberOfRawMeasurements !== null) {
            queryParameters = queryParameters.set('numberOfRawMeasurements', <any>numberOfRawMeasurements);
        }
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }
        if (variableCategoryName !== undefined && variableCategoryName !== null) {
            queryParameters = queryParameters.set('variableCategoryName', <any>variableCategoryName);
        }
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (variableName !== undefined && variableName !== null) {
            queryParameters = queryParameters.set('variableName', <any>variableName);
        }
        if (updatedAt !== undefined && updatedAt !== null) {
            queryParameters = queryParameters.set('updatedAt', <any>updatedAt);
        }
        if (sourceName !== undefined && sourceName !== null) {
            queryParameters = queryParameters.set('sourceName', <any>sourceName);
        }
        if (earliestMeasurementTime !== undefined && earliestMeasurementTime !== null) {
            queryParameters = queryParameters.set('earliestMeasurementTime', <any>earliestMeasurementTime);
        }
        if (latestMeasurementTime !== undefined && latestMeasurementTime !== null) {
            queryParameters = queryParameters.set('latestMeasurementTime', <any>latestMeasurementTime);
        }
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }
        if (lastSourceName !== undefined && lastSourceName !== null) {
            queryParameters = queryParameters.set('lastSourceName', <any>lastSourceName);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (includePublic !== undefined && includePublic !== null) {
            queryParameters = queryParameters.set('includePublic', <any>includePublic);
        }
        if (manualTracking !== undefined && manualTracking !== null) {
            queryParameters = queryParameters.set('manualTracking', <any>manualTracking);
        }
        if (clientId !== undefined && clientId !== null) {
            queryParameters = queryParameters.set('clientId', <any>clientId);
        }
        if (upc !== undefined && upc !== null) {
            queryParameters = queryParameters.set('upc', <any>upc);
        }
        if (effectOrCause !== undefined && effectOrCause !== null) {
            queryParameters = queryParameters.set('effectOrCause', <any>effectOrCause);
        }
        if (publicEffectOrCause !== undefined && publicEffectOrCause !== null) {
            queryParameters = queryParameters.set('publicEffectOrCause', <any>publicEffectOrCause);
        }
        if (exactMatch !== undefined && exactMatch !== null) {
            queryParameters = queryParameters.set('exactMatch', <any>exactMatch);
        }
        if (variableCategoryId !== undefined && variableCategoryId !== null) {
            queryParameters = queryParameters.set('variableCategoryId', <any>variableCategoryId);
        }
        if (includePrivate !== undefined && includePrivate !== null) {
            queryParameters = queryParameters.set('includePrivate', <any>includePrivate);
        }
        if (searchPhrase !== undefined && searchPhrase !== null) {
            queryParameters = queryParameters.set('searchPhrase', <any>searchPhrase);
        }
        if (synonyms !== undefined && synonyms !== null) {
            queryParameters = queryParameters.set('synonyms', <any>synonyms);
        }
        if (taggedVariableId !== undefined && taggedVariableId !== null) {
            queryParameters = queryParameters.set('taggedVariableId', <any>taggedVariableId);
        }
        if (tagVariableId !== undefined && tagVariableId !== null) {
            queryParameters = queryParameters.set('tagVariableId', <any>tagVariableId);
        }
        if (joinVariableId !== undefined && joinVariableId !== null) {
            queryParameters = queryParameters.set('joinVariableId', <any>joinVariableId);
        }
        if (parentUserTagVariableId !== undefined && parentUserTagVariableId !== null) {
            queryParameters = queryParameters.set('parentUserTagVariableId', <any>parentUserTagVariableId);
        }
        if (childUserTagVariableId !== undefined && childUserTagVariableId !== null) {
            queryParameters = queryParameters.set('childUserTagVariableId', <any>childUserTagVariableId);
        }
        if (ingredientUserTagVariableId !== undefined && ingredientUserTagVariableId !== null) {
            queryParameters = queryParameters.set('ingredientUserTagVariableId', <any>ingredientUserTagVariableId);
        }
        if (ingredientOfUserTagVariableId !== undefined && ingredientOfUserTagVariableId !== null) {
            queryParameters = queryParameters.set('ingredientOfUserTagVariableId', <any>ingredientOfUserTagVariableId);
        }
        if (commonOnly !== undefined && commonOnly !== null) {
            queryParameters = queryParameters.set('commonOnly', <any>commonOnly);
        }
        if (userOnly !== undefined && userOnly !== null) {
            queryParameters = queryParameters.set('userOnly', <any>userOnly);
        }
        if (includeTags !== undefined && includeTags !== null) {
            queryParameters = queryParameters.set('includeTags', <any>includeTags);
        }
        if (recalculate !== undefined && recalculate !== null) {
            queryParameters = queryParameters.set('recalculate', <any>recalculate);
        }
        if (variableId !== undefined && variableId !== null) {
            queryParameters = queryParameters.set('variableId', <any>variableId);
        }
        if (concise !== undefined && concise !== null) {
            queryParameters = queryParameters.set('concise', <any>concise);
        }
        if (refresh !== undefined && refresh !== null) {
            queryParameters = queryParameters.set('refresh', <any>refresh);
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Variable>>(`${this.basePath}/v3/variables`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Post or update user tags or ingredients
     * This endpoint allows users to tag foods with their ingredients.  This information will then be used to infer the user intake of the different ingredients by just entering the foods. The inferred intake levels will then be used to determine the effects of different nutrients on the user during analysis.
     * @param body Contains the new user tag data
     * @param userId User&#39;s id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postUserTags(body: UserTag, userId?: number, observe?: 'body', reportProgress?: boolean): Observable<CommonResponse>;
    public postUserTags(body: UserTag, userId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CommonResponse>>;
    public postUserTags(body: UserTag, userId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CommonResponse>>;
    public postUserTags(body: UserTag, userId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postUserTags.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<CommonResponse>(`${this.basePath}/v3/userTags`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update User Settings for a Variable
     * Users can change the parameters used in analysis of that variable such as the expected duration of action for a variable to have an effect, the estimated delay before the onset of action. In order to filter out erroneous data, they are able to set the maximum and minimum reasonable daily values for a variable.
     * @param userVariables Variable user settings data
     * @param includePrivate Include user-specific variables in results
     * @param clientId Your QuantiModo client id can be obtained by creating an app at https://builder.quantimo.do
     * @param includePublic Include variables the user has no measurements for
     * @param searchPhrase Ex: %Body Fat%
     * @param exactMatch Require exact match
     * @param manualTracking Only include variables tracked manually by the user
     * @param variableCategoryName Options: Activities, Books, Causes of Illness, Cognitive Performance, Conditions, Emotions, Environment, Foods, Location, Miscellaneous, Movies and TV, Music, Nutrients, Payments, Physical Activity, Physique, Sleep, Social Interactions, Software, Symptoms, Treatments, Vital Signs, Goals
     * @param variableCategoryId Ex: 13
     * @param synonyms Ex: McDonalds hotcake
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postUserVariables(userVariables: Array<Variable>, includePrivate?: boolean, clientId?: string, includePublic?: boolean, searchPhrase?: string, exactMatch?: boolean, manualTracking?: boolean, variableCategoryName?: string, variableCategoryId?: number, synonyms?: string, observe?: 'body', reportProgress?: boolean): Observable<CommonResponse>;
    public postUserVariables(userVariables: Array<Variable>, includePrivate?: boolean, clientId?: string, includePublic?: boolean, searchPhrase?: string, exactMatch?: boolean, manualTracking?: boolean, variableCategoryName?: string, variableCategoryId?: number, synonyms?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CommonResponse>>;
    public postUserVariables(userVariables: Array<Variable>, includePrivate?: boolean, clientId?: string, includePublic?: boolean, searchPhrase?: string, exactMatch?: boolean, manualTracking?: boolean, variableCategoryName?: string, variableCategoryId?: number, synonyms?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CommonResponse>>;
    public postUserVariables(userVariables: Array<Variable>, includePrivate?: boolean, clientId?: string, includePublic?: boolean, searchPhrase?: string, exactMatch?: boolean, manualTracking?: boolean, variableCategoryName?: string, variableCategoryId?: number, synonyms?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (userVariables === null || userVariables === undefined) {
            throw new Error('Required parameter userVariables was null or undefined when calling postUserVariables.');
        }










        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (includePrivate !== undefined && includePrivate !== null) {
            queryParameters = queryParameters.set('includePrivate', <any>includePrivate);
        }
        if (clientId !== undefined && clientId !== null) {
            queryParameters = queryParameters.set('clientId', <any>clientId);
        }
        if (includePublic !== undefined && includePublic !== null) {
            queryParameters = queryParameters.set('includePublic', <any>includePublic);
        }
        if (searchPhrase !== undefined && searchPhrase !== null) {
            queryParameters = queryParameters.set('searchPhrase', <any>searchPhrase);
        }
        if (exactMatch !== undefined && exactMatch !== null) {
            queryParameters = queryParameters.set('exactMatch', <any>exactMatch);
        }
        if (manualTracking !== undefined && manualTracking !== null) {
            queryParameters = queryParameters.set('manualTracking', <any>manualTracking);
        }
        if (variableCategoryName !== undefined && variableCategoryName !== null) {
            queryParameters = queryParameters.set('variableCategoryName', <any>variableCategoryName);
        }
        if (variableCategoryId !== undefined && variableCategoryId !== null) {
            queryParameters = queryParameters.set('variableCategoryId', <any>variableCategoryId);
        }
        if (synonyms !== undefined && synonyms !== null) {
            queryParameters = queryParameters.set('synonyms', <any>synonyms);
        }

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<CommonResponse>(`${this.basePath}/v3/variables`,
            userVariables,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reset user settings for a variable to defaults
     * Reset user settings for a variable to defaults
     * @param variableId Id of the variable whose measurements should be deleted
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public resetUserVariableSettings(variableId: UserVariableDelete, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public resetUserVariableSettings(variableId: UserVariableDelete, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public resetUserVariableSettings(variableId: UserVariableDelete, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public resetUserVariableSettings(variableId: UserVariableDelete, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (variableId === null || variableId === undefined) {
            throw new Error('Required parameter variableId was null or undefined when calling resetUserVariableSettings.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (access_token) required
        if (this.configuration.apiKeys["access_token"]) {
            queryParameters = queryParameters.set('access_token', this.configuration.apiKeys["access_token"]);
        }

        // authentication (quantimodo_oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/v3/userVariables/reset`,
            variableId,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
